# Generated by Django 3.2.5 on 2021-07-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210716_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
