# Generated by Django 3.2.5 on 2021-07-16 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
