# Generated by Django 3.2.5 on 2021-07-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_presence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='status',
        ),
        migrations.AddField(
            model_name='presence',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='is_insterested',
            field=models.BooleanField(default=False),
        ),
    ]
