# Generated by Django 3.2.5 on 2021-07-18 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20210716_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('user', 'event')},
        ),
    ]
