# Generated by Django 3.2.5 on 2021-07-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_presence_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='is_insterested',
            new_name='is_interested',
        ),
    ]
